// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjCgNy9rYdSOK3bCxKxZIK_e6ZUZIiywI',
    appId: '1:865180060034:web:1eef0116fadd5e5f50279b',
    messagingSenderId: '865180060034',
    projectId: 'marketit-b5e90',
    authDomain: 'marketit-b5e90.firebaseapp.com',
    storageBucket: 'marketit-b5e90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpiCaaGw-ACfG-uYyQYQjCGhvQuCfmGkg',
    appId: '1:865180060034:android:b08a14bd0d5e4f3f50279b',
    messagingSenderId: '865180060034',
    projectId: 'marketit-b5e90',
    storageBucket: 'marketit-b5e90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAphRsytJTI6vrxBcLmz34MfZwcPIfwFPw',
    appId: '1:865180060034:ios:63348f5020e7dc6c50279b',
    messagingSenderId: '865180060034',
    projectId: 'marketit-b5e90',
    storageBucket: 'marketit-b5e90.appspot.com',
    iosBundleId: 'com.example.marketit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAphRsytJTI6vrxBcLmz34MfZwcPIfwFPw',
    appId: '1:865180060034:ios:63348f5020e7dc6c50279b',
    messagingSenderId: '865180060034',
    projectId: 'marketit-b5e90',
    storageBucket: 'marketit-b5e90.appspot.com',
    iosBundleId: 'com.example.marketit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjCgNy9rYdSOK3bCxKxZIK_e6ZUZIiywI',
    appId: '1:865180060034:web:1b423c7c580584e350279b',
    messagingSenderId: '865180060034',
    projectId: 'marketit-b5e90',
    authDomain: 'marketit-b5e90.firebaseapp.com',
    storageBucket: 'marketit-b5e90.appspot.com',
  );
}
